name: yatrim
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.5

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter


  intl: ^0.20.2
  package_info_plus: ^8.3.0
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  get_storage: ^2.1.1
  google_sign_in: ^6.2.2
  flutter_svg: ^2.0.9
  hijri: ^3.0.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  flutter_screenutil: ^5.9.3
  share_plus: ^10.1.2
  url_launcher: ^6.3.1
  easy_localization:
  country_code_picker: ^3.1.0
  flutter_launcher_icons: ^0.14.2
  

# flutter_launcher_icons:
#   #  image_path: "assets/images/icon-128x128.png"
#   image_path_android: "assets/image/app_logo.png"
#   image_path_ios: "assets/image/app_logo.png"
#   android: true # can specify file name here e.g. "ic_launcher"
#   ios: true # can specify file name here e.g. "My-Launcher-Icon"
dev_dependencies:
  
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^5.0.0
  

flutter:

  
  uses-material-design: true

  assets:
    - assets/image/
    - assets/icons/
    - assets/langs/

 
