name: Build APK and Publish Release

on:
  push:
    tags:
      - 'v*' # Trigger on new version tags (e.g., v1.0.0)
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    name: Build APK
    runs-on: windows-latest # Changed from ubuntu-latest to windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'

      - name: Get Flutter packages
        run: flutter pub get

      # --- DIAGNOSTIC STEP (Windows PowerShell version) ---
      # This step helps debug the file path issue using Windows commands
      - name: List directory contents for debugging
        run: |
          Write-Host "Listing contents of lib/app/modules/ to check for case sensitivity issues..."
          Get-ChildItem -Path "lib/app/modules/" -Recurse | Format-Table Name, FullName
        shell: powershell

      - name: Build APK
        run: flutter build apk --release

      - name: Find and prepare APK path for upload (Windows version)
        id: find_apk
        run: |
          $APK_PATH = Get-ChildItem -Path "build/app/outputs/flutter-apk" -Filter "app-release.apk" -Recurse | Select-Object -First 1 -ExpandProperty FullName
          if (-not $APK_PATH) {
            Write-Host "ERROR: app-release.apk not found!"
            exit 1
          }
          Write-Host "Found APK at $APK_PATH"
          # Create a predictable directory for the artifact
          New-Item -ItemType Directory -Force -Path "artifacts"
          Copy-Item -Path $APK_PATH -Destination "artifacts/app-release.apk"
          Write-Host "APK copied to artifacts/app-release.apk"
        shell: powershell

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: artifacts/app-release.apk

  publish-release:
    name: Publish Release
    needs: build
    runs-on: windows-latest # Changed from ubuntu-latest to windows-latest
    permissions:
      contents: write

    steps:
      - name: Download APK artifact
        uses: actions/download-artifact@v4
        with:
          name: app-release-apk
          path: .

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: "Automated release for version ${{ github.ref_name }}"
          files: app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
